name: BuildQtMac
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-11
    steps:
    - name: "Clone source"
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: "Clone Qt"
      run: |
        git clone https://github.com/qt/qt5
        pushd qt5
        git checkout v5.15.8-lts-lgpl
        git submodule update --init {qtbase,qtsvg,qtdeclarative,qtgraphicaleffects,qtimageformats,qtquickcontrols2}
        popd
    - name: "Build"
      run: |
        mkdir qt5-build
        pushd qt5-build
        ../qt5/configure -platform macx-clang -prefix $HOME/qt5.15.8-x86_64-macos-static -release -static -opensource -confirm-license  -no-pch -no-iconv -no-dbus -no-icu -no-fontconfig -no-freetype -qt-harfbuzz -qt-doubleconversion -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake tools -nomake examples -nomake tests -no-feature-pdf -no-feature-sql -no-feature-sqlmodel -no-feature-testlib -no-feature-testlib_selfcover -no-feature-qml-profiler -no-feature-qml-preview
        make
        mkdir $HOME/qt5.15.8-x86_64-macos-static
        make install
        popd
    - name: "Package"
      shell: bash
      run: |
        tar caf qt5.15.8-x86_64-macos-static.tar.xz $HOME/qt5.15.8-x86_64-macos-static
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: qt5.15.8-x86_64-macos-static
        path: qt5.15.8-x86_64-macos-static.tar.xz
        retention-days: 15
