name: BuildIt
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: "Clone source"
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: "Setup msvc"
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    - name: "Build"
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" "-DCMAKE_BUILD_TYPE:STRING=Release" ..
        cmake --build .
    - name: "Package"
      shell: bash
      run: |
        PATH="$PATH:$Qt5_DIR/bin" ./make-release.sh build
        7z a cslol-manager-windows.zip cslol-manager/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: cslol-manager-windows
        path: cslol-manager-windows.zip
        retention-days: 15
